FROM python:3.12-slim

WORKDIR /app

# Install poetry
RUN pip install poetry watchdog

# Copy project files
COPY pyproject.toml .

# Install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-root
